# Generated by Django 4.1.2 on 2022-12-18 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
        migrations.AddField(
            model_name='contact',
            name='email_address',
            field=models.EmailField(default='test email', max_length=150),
        ),
        migrations.AddField(
            model_name='contact',
            name='first_name',
            field=models.CharField(default='test first name', max_length=50),
        ),
        migrations.AddField(
            model_name='contact',
            name='last_name',
            field=models.CharField(default='test last name', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.CharField(default='test message', max_length=1000),
        ),
    ]
