# Generated by Django 4.1 on 2023-01-20 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_contact_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created']},
        ),
    ]
